### ISSUE TITLE
Consider using org.infinispan.commons.api

### ISSUE THREAD

**Issue by TuomasKiviaho** [zbiljic/shiro-infinispan#1]
It seems that internals have once again changes between 7.x and 8.x of Infinispan in a non-binary compatible way. Could you refactor the implementation to utilize `BasicCache` and `BasicCacheContainer` instead? As a bonus the dependency to infinispan-core that is needed for `new org.infinispan.manager.DefaultCacheManager` would become optional and only `infinispan-commons` is would be required when cache container is provided from outside.

**Comment by zbiljic** [comment]
Hi, I have refactored the code per your suggestion. It still depends on Infinispan 6.x, but only `infinispan-commons` is required. You can now also set `cacheContainer` instance through `shiro.ini` configuration.

I would appreciate if you can test if it works for your case now, as I have no easy means currently to test it.

**Comment by TuomasKiviaho** [comment]
Thanks a bunch. It looks quite identical to my patch except that the quality is way better
